### ISSUE TITLE
`strip!': can't modify frozen String (RuntimeError)

### ISSUE THREAD

**Issue by Tyilo** [htty/htty#128]
When installing and running `htty` on OS X 10.10.5, I get the following error:

```
$ gem install htty
Fetching: mime-types-1.25.1.gem (100%)
Fetching: htty-1.5.0.gem (100%)
Successfully installed mime-types-1.25.1
Successfully installed htty-1.5.0
2 gems installed
Installing ri documentation for mime-types-1.25.1...
Installing ri documentation for htty-1.5.0...
Installing RDoc documentation for mime-types-1.25.1...
Installing RDoc documentation for htty-1.5.0...
$ htty
/usr/local/Cellar/ruby193/1.9.3-p551_1/lib/ruby/1.9.1/rubygems/version.rb:191:in `strip!': can't modify frozen String (RuntimeError)
	from /usr/local/Cellar/ruby193/1.9.3-p551_1/lib/ruby/1.9.1/rubygems/version.rb:191:in `initialize'
	from /usr/local/lib/ruby/gems/1.9.1/gems/htty-1.5.0/lib/htty/requests_util.rb:121:in `new'
	from /usr/local/lib/ruby/gems/1.9.1/gems/htty-1.5.0/lib/htty/requests_util.rb:121:in `<module:RequestsUtil>'
	from /usr/local/lib/ruby/gems/1.9.1/gems/htty-1.5.0/lib/htty/requests_util.rb:11:in `<top (required)>'
	from /usr/local/Cellar/ruby193/1.9.3-p551_1/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /usr/local/Cellar/ruby193/1.9.3-p551_1/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'	from /usr/local/lib/ruby/gems/1.9.1/gems/htty-1.5.0/lib/htty/request.rb:11:in `<top (required)>'
	from /usr/local/Cellar/ruby193/1.9.3-p551_1/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /usr/local/Cellar/ruby193/1.9.3-p551_1/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /usr/local/lib/ruby/gems/1.9.1/gems/htty-1.5.0/lib/htty/cli/commands/userinfo_set.rb:1:in `<top (required)>'
	from /usr/local/Cellar/ruby193/1.9.3-p551_1/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /usr/local/Cellar/ruby193/1.9.3-p551_1/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /usr/local/lib/ruby/gems/1.9.1/gems/htty-1.5.0/lib/htty/cli/commands/address.rb:8:in `<top (required)>'
	from /usr/local/Cellar/ruby193/1.9.3-p551_1/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /usr/local/Cellar/ruby193/1.9.3-p551_1/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /usr/local/lib/ruby/gems/1.9.1/gems/htty-1.5.0/lib/htty/cli/commands.rb:40:in `block in <top (required)>'
	from /usr/local/lib/ruby/gems/1.9.1/gems/htty-1.5.0/lib/htty/cli/commands.rb:38:in `glob'
	from /usr/local/lib/ruby/gems/1.9.1/gems/htty-1.5.0/lib/htty/cli/commands.rb:38:in `<top (required)>'
	from /usr/local/Cellar/ruby193/1.9.3-p551_1/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /usr/local/Cellar/ruby193/1.9.3-p551_1/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /usr/local/lib/ruby/gems/1.9.1/gems/htty-1.5.0/lib/htty/cli.rb:1:in `<top (required)>'
	from /usr/local/Cellar/ruby193/1.9.3-p551_1/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /usr/local/Cellar/ruby193/1.9.3-p551_1/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /usr/local/lib/ruby/gems/1.9.1/gems/htty-1.5.0/lib/htty.rb:6:in `block in <top (required)>'
	from /usr/local/lib/ruby/gems/1.9.1/gems/htty-1.5.0/lib/htty.rb:4:in `glob'
	from /usr/local/lib/ruby/gems/1.9.1/gems/htty-1.5.0/lib/htty.rb:4:in `<top (required)>'
	from /usr/local/Cellar/ruby193/1.9.3-p551_1/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /usr/local/Cellar/ruby193/1.9.3-p551_1/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /usr/local/lib/ruby/gems/1.9.1/gems/htty-1.5.0/bin/htty:3:in `<top (required)>'
	from /usr/local/bin/htty:23:in `load'
	from /usr/local/bin/htty:23:in `<main>'
```

**Comment by njonsson** [comment]
Fixed in https://github.com/htty/htty/commit/b70bdff6fbe1fa318de69b21db7cb9bfc757628d and [v1.5.1](https://rubygems.org/gems/htty/versions/1.5.1).
